import {supabaseClient} from './db.js';
import {toast,loading,emptyState,modal} from './ui.js';
import {escapeHtml} from './utils.js';
const esc=v=>escapeHtml(v??'');
const TYPES=['all','lead','company','deal','payment','invoice','website_project','qr_project','delivery','system'];
async function loadActivities(type='all',search=''){
 let q=supabaseClient().from('activities').select('id,type,title,description,metadata,created_at,user_id,lead_id,company_id').order('created_at',{ascending:false}).limit(200);
 if(type!=='all')q=q.eq('type',type);
 const r=await q;if(r.error)throw r.error;const needle=search.trim().toLowerCase();
 return(r.data||[]).filter(x=>!needle||[x.title,x.description,x.type].some(v=>String(v||'').toLowerCase().includes(needle)));
}
function rows(items){if(!items.length)return `<div class="card">${emptyState('No activity found','CRM events will appear here automatically.')}</div>`;return `<section class="table-card"><table><thead><tr><th>Event</th><th>Type</th><th>Description</th><th>Time</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td><strong>${esc(x.title)}</strong></td><td><span class="badge">${esc(x.type)}</span></td><td>${esc(x.description||'—')}</td><td>${new Date(x.created_at).toLocaleString()}</td><td><button class="icon-btn" data-activity="${x.id}">→</button></td></tr>`).join('')}</tbody></table></section>`}
function details(item){if(!item)return;modal({title:'Activity details',body:`<div class="detail-grid"><section><span class="eyebrow">${esc(item.type)}</span><h3>${esc(item.title)}</h3><p>${esc(item.description||'No description')}</p></section><section><span class="eyebrow">CONTEXT</span><div class="info-list"><div><span>Created</span><strong>${new Date(item.created_at).toLocaleString()}</strong></div><div><span>Lead</span><strong>${esc(item.lead_id||'—')}</strong></div><div><span>Company</span><strong>${esc(item.company_id||'—')}</strong></div></div></section></div><section><h3>Metadata</h3><pre class="code-block">${esc(JSON.stringify(item.metadata||{},null,2))}</pre></section>`})}
export async function render(){const host=document.querySelector('#page');host.innerHTML=loading('Loading activity…');try{host.innerHTML=`<div class="page-head"><div><span class="eyebrow">AUDIT TRAIL</span><h2>Activities</h2><p class="muted">A database-backed timeline of important CRM events.</p></div></div><section class="card"><div class="form-grid"><label>Type<select id="activity-type">${TYPES.map(t=>`<option value="${t}">${t==='all'?'All events':t}</option>`).join('')}</select></label><label>Search<input id="activity-search" placeholder="Search events…"></label></div></section><div id="activity-list"></div>`;const list=host.querySelector('#activity-list');const refresh=async()=>{list.innerHTML=loading('Loading events…');try{const items=await loadActivities(host.querySelector('#activity-type').value,host.querySelector('#activity-search').value);list.innerHTML=rows(items);list.querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>details(items.find(x=>x.id===b.dataset.activity)))}catch(e){list.innerHTML=emptyState('Activities unavailable',e.message)}};host.querySelector('#activity-type').onchange=refresh;let timer;host.querySelector('#activity-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(refresh,200)};await refresh()}catch(e){host.innerHTML=emptyState('Activities unavailable',e.message);toast(e.message,'error')}}
