import {supabaseClient} from './db.js';
import {getCurrentUser} from './auth.js';
import {toast,emptyState,loading,modal} from './ui.js';
import {escapeHtml,qs,qsa} from './utils.js';
import {recordActivity} from './activity.js';
import {aiAnalyze,aiDraft} from './server-api.js';

const db=()=>supabaseClient();
const actions=['qualify_lead','reply','create_followup','update_lead','change_status','request_human','recommend_service','create_activity','do_nothing'];
const modes=['manual','ai_draft','assisted','automation_ready'];
const decisionStatuses=['pending','approved','rejected','executed'];
const variables=['company_name','contact_name','city','service','website','preview_url'];

function safe(v){return escapeHtml(v??'');}
function scoreContext({lead,company,conversation}){
  let score=Number(lead?.score||0);const reasons=[];
  if(company?.website){score+=8;reasons.push('Company website is present.')}else{score-=8;reasons.push('Company has no website recorded.');}
  if(company?.email||company?.phone){score+=6;reasons.push('A direct contact channel is available.');}
  if(lead?.status==='interested'){score+=15;reasons.push('Lead is marked interested.');}
  if(lead?.status==='qualified'){score+=10;reasons.push('Lead is qualified.');}
  if(lead?.priority==='high'){score+=10;reasons.push('Lead priority is high.');}
  if(conversation?.status==='handoff'){score-=20;reasons.push('Conversation already requires human handling.');}
  return {score:Math.max(0,Math.min(100,score)),reasons};
}
function inferAction({lead,conversation,score}){
  if(conversation?.status==='handoff')return 'do_nothing';
  if(lead?.status==='negotiating'||lead?.status==='payment')return 'request_human';
  if(score>=70||lead?.status==='qualified'||lead?.status==='interested')return 'create_followup';
  return 'qualify_lead';
}
function renderDecisionCard(d){return `<article class="card ai-decision-card"><div class="card-head"><div><span class="eyebrow">DECISION</span><h3>${safe(d.action||'—')}</h3></div><span class="badge">${safe(d.approval_status||'pending')}</span></div><div class="lead-kpis"><div><span>Score</span><strong>${Number(d.confidence||0)}%</strong></div><div><span>Action</span><strong>${safe(d.action||'—')}</strong></div><div><span>Mode</span><strong>${safe(d.mode||'—')}</strong></div></div><p>${safe(d.reason||'No explanation recorded.')}</p></article>`}

export async function evaluateLead(leadId,{createLog=true}={}){
  const r=await db().from('leads').select('id,name,status,score,priority,recommended_service,company_id,companies(id,name,industry,city,website,email,phone)').eq('id',leadId).single();
  if(r.error)throw r.error;const c=r.data?.companies;
  const cr=await db().from('conversations').select('id,status,last_message_at').eq('lead_id',leadId).order('updated_at',{ascending:false}).limit(1).maybeSingle();
  if(cr.error)throw cr.error;const {score,reasons}=scoreContext({lead:r.data,company:c,conversation:cr.data});const action=inferAction({lead:r.data,conversation:cr.data,score});const confidence=Math.round(Math.min(99,60+Math.abs(score-50)*.7));
  const reason=`Deterministic-safe fallback engine (server AI provider unavailable): ${reasons.join(' ')} Recommended action: ${action}.`;
  try { const real=await aiAnalyze({leadId,conversationId:cr.data?.id||null}); return {...real.decision,score:real.analysis.lead_score,recommended_action:real.analysis.recommended_action,provider:'openai'} } catch(realError) { if(!realError.fallback && realError.status!==503) throw realError; }
  const decision={lead_id:leadId,conversation_id:cr.data?.id||null,decision:action,confidence,reason,action,approval_status:'pending',mode:'assisted',input_context_ref:{engine:'deterministic-safe-v1',inputs:['lead','company','latest_conversation'],generated_at:new Date().toISOString()}};
  if(createLog){const x=await db().from('ai_decisions').insert(decision).select().single();if(x.error)throw x.error;return {...x.data,score,recommended_action:action};}
  return {...decision,score,recommended_action:action};
}

async function loadAgents(){const r=await db().from('ai_agents').select('id,name,status,enabled,default_mode,confidence_threshold,handoff_threshold,assigned_channels,assigned_campaigns,configuration,created_at,updated_at').order('updated_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
async function saveAgent(data,id){const u=await getCurrentUser();if(!u)throw new Error('Authentication required.');const payload={...data,created_by:u.id};const r=id?await db().from('ai_agents').update(payload).eq('id',id).select().single():await db().from('ai_agents').insert(payload).select().single();if(r.error)throw r.error;return r.data}
function agentForm(agent={}){const m=modal({title:agent.id?'Edit AI agent':'New AI agent',body:`<form class="form-grid" id="agent-form"><label>Name<input name="name" required value="${safe(agent.name||'Sales Agent')}"></label><label>Status<select name="status">${['active','paused','disabled'].map(x=>`<option ${agent.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Default mode<select name="default_mode">${modes.map(x=>`<option ${agent.default_mode===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Confidence threshold<input type="number" name="confidence_threshold" min="0" max="100" value="${Number(agent.confidence_threshold??70)}"></label><label>Human handoff threshold<input type="number" name="handoff_threshold" min="0" max="100" value="${Number(agent.handoff_threshold??45)}"></label><label>Enabled<select name="enabled"><option value="true" ${agent.enabled!==false?'selected':''}>Yes</option><option value="false" ${agent.enabled===false?'selected':''}>No</option></select></label><label class="full">Configuration JSON<textarea name="configuration">${safe(JSON.stringify(agent.configuration||{},null,2))}</textarea></label><div class="form-actions"><button type="button" class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary">Save agent</button></div></form>`});m.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button.btn-primary');b.disabled=true;b.textContent='Saving…';try{const fd=new FormData(e.currentTarget);let configuration={};try{configuration=JSON.parse(fd.get('configuration')||'{}')}catch{throw new Error('Configuration must be valid JSON.')}await saveAgent({name:String(fd.get('name')).trim(),status:fd.get('status'),default_mode:fd.get('default_mode'),enabled:fd.get('enabled')==='true',confidence_threshold:Number(fd.get('confidence_threshold')),handoff_threshold:Number(fd.get('handoff_threshold')),configuration},agent.id);toast('AI agent saved','success');m.remove();renderAgentCenter()}catch(x){toast(x.message,'error');b.disabled=false;b.textContent='Save agent'}}}

async function renderAgentCenter(){const host=qs('#page');host.innerHTML=loading('Loading AI Agent…');try{const agents=await loadAgents();host.innerHTML=`<div class="module-head"><div><span class="eyebrow">AI / AGENT CORE</span><h2>AI Agent</h2><p>AI agent configuration with server-side real-provider execution and a deterministic-safe fallback when no provider is configured.</p></div><button class="btn btn-primary" id="new-agent">+ New agent</button></div><div class="metrics metrics-compact"><article class="metric-card"><span>Active agents</span><strong>${agents.filter(a=>a.enabled&&a.status==='active').length}</strong><small>Live database</small></article><article class="metric-card"><span>Pending decisions</span><strong id="pending-decisions">0</strong><small>Live database</small></article><article class="metric-card"><span>Provider</span><strong>Server-side</strong><small>Provider status is reported by Integrations</small></article></div><section class="template-grid">${agents.map(a=>`<article class="card"><div class="card-head"><div><span class="eyebrow">AGENT</span><h3>${safe(a.name)}</h3></div><span class="badge">${safe(a.status)}</span></div><div class="info-list"><div><span>Enabled</span><strong>${a.enabled?'Yes':'No'}</strong></div><div><span>Mode</span><strong>${safe(a.default_mode)}</strong></div><div><span>Confidence threshold</span><strong>${a.confidence_threshold}%</strong></div><div><span>Handoff threshold</span><strong>${a.handoff_threshold}%</strong></div></div><div class="project-actions"><button class="btn btn-ghost" data-edit-agent="${a.id}">Edit</button></div></article>`).join('')||emptyState('No AI agents','Create an agent configuration before enabling AI workflows.')}</section><section class="card"><div class="card-head"><div><span class="eyebrow">AI DECISION LOG</span><h3>Recent decisions</h3></div></div><div id="decision-list">${loading('Loading decisions…')}</div></section>`;qs('#new-agent').onclick=()=>agentForm();qsa('[data-edit-agent]').forEach(b=>b.onclick=async()=>{const r=await db().from('ai_agents').select('*').eq('id',b.dataset.editAgent).single();if(r.error)return toast(r.error.message,'error');agentForm(r.data)});const dr=await db().from('ai_decisions').select('id,decision,confidence,reason,action,approval_status,created_at').order('created_at',{ascending:false}).limit(12);if(dr.error)throw dr.error;qs('#decision-list').innerHTML=dr.data?.map(renderDecisionCard).join('')||emptyState('No AI decisions','Run lead evaluation from a Lead record to create a decision log.');const pr=await db().from('ai_decisions').select('id',{count:'exact',head:true}).eq('approval_status','pending');qs('#pending-decisions').textContent=pr.error?'0':(pr.count||0)}catch(e){host.innerHTML=emptyState('AI Agent unavailable',e.message)}}

export async function render(){await renderAgentCenter()}
export async function openResponseDraft(conversationId){
  const r=await db().from('conversations').select('id,status,lead_id,channel,leads(id,name,company_id,companies(name,city,website))').eq('id',conversationId).single();if(r.error)throw r.error;
  const msgs=await db().from('messages').select('id,sender_type,message,created_at,status').eq('conversation_id',conversationId).order('created_at',{ascending:false}).limit(12);if(msgs.error)throw msgs.error;
  const latest=(msgs.data||[]).find(x=>x.sender_type==='lead');const lead=r.data.leads;let realDraft=null;try{realDraft=await aiDraft({conversationId});}catch(e){if(!e.fallback&&e.status!==503)throw e;}const reason=realDraft?'Draft généré par le provider AI réel, en attente d’approbation humaine.':latest?'Fallback déterministe sécurisé : provider AI indisponible.':'No inbound message is available; draft requires an inbound message.';const suggestion=realDraft?.draft?.draft_body||(latest?`Bonjour ${lead?.name||''}, merci pour votre message. Nous avons bien noté votre demande${lead?.companies?.name?` concernant ${lead.companies.name}`:''}. Un membre de notre équipe peut vous confirmer les prochaines étapes.`:'');
  const m=modal({title:'AI response draft',body:`<div class="alert alert-warn">${realDraft?'Provider AI réel : le brouillon est enregistré et reste soumis à approbation humaine.':'Provider AI indisponible : fallback déterministe sécurisé.'}</div><div class="ai-context-grid"><section class="card"><span class="eyebrow">INCOMING MESSAGE</span><p>${safe(latest?.message||'No inbound message')}</p></section><section class="card"><span class="eyebrow">LEAD CONTEXT</span><p>${safe(lead?.name||'—')} · ${safe(lead?.companies?.name||'—')} · ${safe(lead?.companies?.city||'—')}</p></section></div><label class="full">Suggested response<textarea id="draft-body">${safe(suggestion)}</textarea></label><p class="muted">${safe(reason)}</p><div class="lead-kpis"><div><span>Confidence</span><strong>${realDraft?Number(realDraft.draft?.confidence||75):latest?'72':'0'}%</strong></div><div><span>Approval</span><strong>Pending</strong></div><div><span>External send</span><strong>Human approval</strong></div></div><div class="form-actions"><button class="btn btn-ghost" data-close>Reject</button><button class="btn btn-primary" id="save-draft">Approve draft</button></div>`});qs('#save-draft')?.addEventListener('click',async()=>{const b=qs('#save-draft');b.disabled=true;b.textContent='Saving…';try{const u=await getCurrentUser();let x;if(realDraft?.draft?.id){x=await db().from('ai_drafts').update({draft_body:qs('#draft-body').value.trim(),approval_status:'approved',approved_by:u?.id||null,approved_at:new Date().toISOString()}).eq('id',realDraft.draft.id).select().single()}else{x=await db().from('ai_drafts').insert({conversation_id:conversationId,lead_id:r.data.lead_id,agent_id:null,incoming_message_id:latest?.id||null,draft_body:qs('#draft-body').value.trim(),reasoning_summary:reason,confidence:latest?72:0,approval_status:'approved',mode:'ai_draft',approved_by:u?.id||null,approved_at:new Date().toISOString()}).select().single()}if(x.error)throw x.error;await db().from('ai_decisions').insert({lead_id:r.data.lead_id,conversation_id:conversationId,decision:'reply',confidence:latest?72:0,reason,action:'reply',approval_status:'approved',mode:'ai_draft',context_ref:{engine:'deterministic-safe-v1',draft_id:x.data.id}});await recordActivity({type:'ai_draft_approved',title:'AI response draft approved',lead_id:r.data.lead_id,metadata:{conversation_id:conversationId,draft_id:x.data.id}});toast('Draft approved and stored — not sent externally','success');m.remove();}catch(e){toast(e.message,'error');b.disabled=false;b.textContent='Approve draft'}})
}
