import {supabaseClient} from './db.js';
import {escapeHtml} from './utils.js';

export async function renderPublicPreview(token){
  document.body.innerHTML='<main class="public-preview-loading"><div class="state"><span class="spinner"></span><h3>Loading preview…</h3><p>Please wait.</p></div></main>';
  if(!token){document.body.innerHTML='<main class="public-preview-error"><div class="state"><h3>Preview link is incomplete</h3><p>This preview does not contain a valid access token.</p></div></main>';return}
  const db=supabaseClient();const {data,error}=await db.rpc('get_website_preview',{p_token:token});
  if(error||!data?.length){document.body.innerHTML='<main class="public-preview-error"><div class="state"><h3>Preview unavailable</h3><p>This preview may have expired, been revoked, or is no longer available.</p></div></main>';return}
  const item=data[0];document.title=`Preview — ${item.company_name||'Website'}`;
  await db.rpc('record_website_preview_view',{p_token:token,p_user_agent:navigator.userAgent}).catch(()=>{});
  document.body.innerHTML=`<div class="preview-toolbar"><span>CLIENT PREVIEW</span><strong>${escapeHtml(item.company_name||'Website')}</strong><small>Viewing only · Source files are not included</small></div><iframe class="preview-frame" title="Website preview" sandbox="allow-forms allow-modals allow-popups allow-presentation allow-scripts" referrerpolicy="no-referrer"></iframe><section class="client-review-panel"><div><span class="eyebrow">CLIENT REVIEW</span><h2>Review your website</h2><p>Please approve the preview or tell the agency what you would like changed.</p></div><div class="review-actions"><button class="btn btn-primary" id="client-approve">Approve website</button><button class="btn btn-ghost" id="client-revision">Request a revision</button></div><div id="review-message" class="form-error"></div></section>`;
  document.querySelector('.preview-frame').srcdoc=item.html;
  const message=document.querySelector('#review-message');
  document.querySelector('#client-approve').onclick=async()=>{const b=document.querySelector('#client-approve');b.disabled=true;b.textContent='Submitting…';try{const r=await db.rpc('client_review_website_preview',{p_token:token,p_action:'approve',p_message:null});if(r.error)throw r.error;message.className='form-success';message.textContent='Thank you. Your approval has been recorded. The agency can now verify the payment gate.';document.querySelectorAll('.review-actions button').forEach(x=>x.disabled=true)}catch(e){message.className='form-error';message.textContent=e.message||'Unable to record approval.';b.disabled=false;b.textContent='Approve website'}};
  document.querySelector('#client-revision').onclick=async()=>{const body=`<form id="revision-form" class="form-grid"><label class="full">What would you like us to change?<textarea name="message" required minlength="1" maxlength="5000" placeholder="Describe the requested changes…"></textarea></label><div class="form-actions"><button type="button" class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary">Send revision request</button></div></form>`;const wrap=document.createElement('div');wrap.innerHTML=`<div class="client-review-modal">${body}</div>`;document.body.appendChild(wrap);const form=wrap.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('.btn-primary');b.disabled=true;b.textContent='Sending…';try{const r=await db.rpc('client_review_website_preview',{p_token:token,p_action:'request_revision',p_message:new FormData(form).get('message')});if(r.error)throw r.error;wrap.remove();message.className='form-success';message.textContent='Your revision request has been sent to the agency.';document.querySelectorAll('.review-actions button').forEach(x=>x.disabled=true)}catch(x){b.disabled=false;b.textContent='Send revision request';form.insertAdjacentHTML('beforeend',`<div class="form-error">${escapeHtml(x.message||'Unable to send request.')}</div>`)}};wrap.querySelector('[data-close]').onclick=()=>wrap.remove()};
}
