import {supabaseClient} from './db.js';
import {toast,loading,emptyState,modal} from './ui.js';
import {escapeHtml,qs} from './utils.js';
const esc=v=>escapeHtml(v??'');
async function openForm(existing={}){
  const m=modal({title:existing.id?'Edit service':'New service',body:`<form id="service-form" class="form-grid"><label>Name<input name="name" required maxlength="160" value="${esc(existing.name||'')}"></label><label>Price<input name="price" type="number" min="0" step="0.01" required value="${existing.price??0}"></label><label>Currency<input name="currency" maxlength="3" required value="${esc(existing.currency||'MAD')}"></label><label>Active<select name="active"><option value="true" ${existing.active!==false?'selected':''}>Active</option><option value="false" ${existing.active===false?'selected':''}>Inactive</option></select></label><label class="full">Description<textarea name="description" maxlength="1000">${esc(existing.description||'')}</textarea></label><div class="form-actions"><button type="button" class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary">Save service</button></div></form>`});
  m.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const payload={name:String(fd.get('name')||'').trim(),description:String(fd.get('description')||'').trim()||null,price:Number(fd.get('price')),currency:String(fd.get('currency')||'MAD').trim().toUpperCase(),active:fd.get('active')==='true'};if(!payload.name||!Number.isFinite(payload.price)||payload.price<0||!/^[A-Z]{3}$/.test(payload.currency))return toast('Check service name, price and 3-letter currency.','error');const r=existing.id?await supabaseClient().from('services').update(payload).eq('id',existing.id).select().single():await supabaseClient().from('services').insert(payload).select().single();if(r.error)return toast(r.error.message,'error');toast('Service saved','success');m.remove();render()};
}
export async function render(){const host=qs('#page');host.innerHTML=loading('Loading services…');const r=await supabaseClient().from('services').select('id,name,description,price,currency,active,created_at,updated_at').order('active',{ascending:false}).order('name');if(r.error){host.innerHTML=emptyState('Services unavailable',r.error.message);return}const rows=r.data||[];host.innerHTML=`<div class="module-head"><div><span class="eyebrow">CATALOG / SERVICES</span><h2>Services</h2><p>Commercial services used by Deals, Website Projects, QR Projects and billing.</p></div><button class="btn btn-primary" id="new-service">+ New service</button></div><section class="table-card"><table><thead><tr><th>Service</th><th>Description</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.description||'—')}</td><td>${Number(s.price).toLocaleString()} ${esc(s.currency)}</td><td><span class="badge">${s.active?'active':'inactive'}</span></td><td><button class="icon-btn" data-edit="${s.id}">✎</button></td></tr>`).join('')||`<tr><td colspan="5">${emptyState('No services','Add a service to make it available to Deals and Projects.')}</td></tr>`}</tbody></table></section>`;qs('#new-service').onclick=()=>openForm();host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const x=await supabaseClient().from('services').select('*').eq('id',b.dataset.edit).single();if(x.error)return toast(x.error.message,'error');openForm(x.data)})}
