import crypto from 'node:crypto';
import {getAdminDb,requireRole} from '../core/db.js';
import {createProviders} from '../providers/index.js';
import {integrationLimiters} from '../core/rate-limit.js';
import {ProviderError} from '../providers/provider.js';

const providers=createProviders();
const ACTIONS=new Set(['reply','qualify_lead','create_followup','recommend_service','request_human','create_activity','do_nothing']);
const VARS=new Set(['company_name','contact_name','city','service','website','preview_url']);
function json(res,status,body){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body));}
function redact(v){if(v===null||v===undefined)return v;if(Array.isArray(v))return v.map(redact);if(typeof v!=='object')return v;const o={};for(const[k,x]of Object.entries(v))o[k]=/key|token|secret|password|authorization|cookie/i.test(k)?'[REDACTED]':redact(x);return o}
function renderTemplate(s,d){let unknown=null;const out=String(s||'').replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g,(_,k)=>{const key=k.toLowerCase();if(!VARS.has(key)){unknown=key;return ''}return String(d[key]??'')});if(unknown)throw new Error(`Unknown template variable: ${unknown}`);return out;}
async function logUsage(db,entry){try{await db.from('ai_usage_logs').insert(entry)}catch(e){console.error('ai usage log failed',e.message)}}
function estimatedCost(model,input=0,output=0){const rates={'gpt-5.6-luna':[0.20,1.20],'gpt-5.6-terra':[2,12],'gpt-5.6-sol':[4,20]};const r=rates[model]||null;return r?((input/1e6)*r[0]+(output/1e6)*r[1]):null}
async function aiAnalyze({user,body}){
  requireRole(user); if(!integrationLimiters.ai.allow(user.id))return {status:429,body:{error:'AI rate limit exceeded'}};
  const db=getAdminDb();const leadId=body.leadId,conversationId=body.conversationId;
  if(!leadId&&!conversationId)return {status:400,body:{error:'leadId or conversationId is required'}};
  let lead=null,company=null,conversation=null,messages=[],knowledge=[];
  if(leadId){const r=await db.from('leads').select('id,name,status,score,priority,recommended_service,notes,company_id,companies(id,name,industry,city,website,email,phone)').eq('id',leadId).single();if(r.error)return {status:404,body:{error:'Lead not found'}};lead=r.data;company=lead.companies;}
  if(conversationId){const r=await db.from('conversations').select('id,status,channel,subject,lead_id,ai_handling').eq('id',conversationId).single();if(r.error)return {status:404,body:{error:'Conversation not found'}};conversation=r.data;if(!leadId){const lr=await db.from('leads').select('id,name,status,score,priority,recommended_service,notes,company_id,companies(id,name,industry,city,website,email,phone)').eq('id',conversation.lead_id).single();if(lr.data){lead=lr.data;company=lr.data.companies}}const mr=await db.from('messages').select('id,sender_type,message,created_at,status').eq('conversation_id',conversationId).order('created_at',{ascending:false}).limit(20);messages=mr.data||[];}
  const kr=await db.from('ai_knowledge_items').select('title,category,content').eq('active',true).order('updated_at',{ascending:false}).limit(50);knowledge=kr.data||[];
  const context={lead,company,conversation,message_history:messages,knowledge}; const started=Date.now();let result;
  try{result=await providers.ai.analyze(context);await logUsage(db,{provider:'openai',model:providers.ai.model,request_type:'analysis',user_id:user.id,lead_id:lead?.id||null,conversation_id:conversation?.id||null,success:true,input_tokens:result.usage?.input_tokens||0,output_tokens:result.usage?.output_tokens||0,total_tokens:result.usage?.total_tokens||0,estimated_cost:estimatedCost(providers.ai.model,result.usage?.input_tokens||0,result.usage?.output_tokens||0),latency_ms:result.latency_ms||Date.now()-started,metadata:{}})}catch(e){await logUsage(db,{provider:'openai',model:providers.ai.model,request_type:'analysis',user_id:user.id,lead_id:lead?.id||null,conversation_id:conversation?.id||null,success:false,error_code:e.code||'AI_ERROR',latency_ms:Date.now()-started,metadata:{}});return {status:e.code==='NOT_CONFIGURED'?503:e.code==='RATE_LIMIT'?429:502,body:{error:e.message,code:e.code,fallback:true}}}
  const a=result.data;const handoff=a.needs_human||a.confidence<0.45||['request_human','complaint','payment_problem','complex_request','out_of_scope'].includes(a.intent);
  const action=ACTIONS.has(a.recommended_action)?a.recommended_action:'do_nothing';
  const decision={lead_id:lead?.id||null,conversation_id:conversation?.id||null,decision:action,confidence:Math.round(a.confidence*100),reason:a.reason,action,approval_status:'pending',mode:'assisted',context_ref:{provider:'openai',model:providers.ai.model,structured:true}};
  const dr=await db.from('ai_decisions').insert(decision).select().single();if(dr.error)return {status:500,body:{error:'AI result could not be stored'}};
  if(handoff&&conversation){await db.from('conversation_handoffs').insert({conversation_id:conversation.id,reason:a.confidence<0.45?'ai_confidence_too_low':a.intent==='complaint'?'complaint':a.intent==='payment_problem'?'complex_request':a.intent==='pricing_request'?'pricing_negotiation':'complex_request',requested_by:user.id,notes:a.reason});await db.from('conversations').update({status:'handoff',ai_handling:false}).eq('id',conversation.id);await db.from('notifications').insert({user_id:user.id,type:'human_handoff',title:'Human handoff required',message:a.reason,lead_id:lead?.id||null,company_id:company?.id||null,source_type:'ai_decision',source_id:dr.data.id});}
  return {status:200,body:{analysis:a,decision:dr.data,fallback:false}};
}
async function aiDraft({user,body}){
  requireRole(user);if(!integrationLimiters.ai.allow(user.id))return {status:429,body:{error:'AI rate limit exceeded'}};if(!body.conversationId)return {status:400,body:{error:'conversationId is required'}};const db=getAdminDb();
  const cr=await db.from('conversations').select('id,status,channel,subject,lead_id,leads(id,name,status,score,priority,recommended_service,companies(id,name,city,website,email,phone))').eq('id',body.conversationId).single();if(cr.error)return {status:404,body:{error:'Conversation not found'}};
  const mr=await db.from('messages').select('id,sender_type,message,created_at,status').eq('conversation_id',body.conversationId).order('created_at',{ascending:false}).limit(20);const kr=await db.from('ai_knowledge_items').select('title,category,content').eq('active',true).order('updated_at',{ascending:false}).limit(50);
  const lead=cr.data.leads, context={lead,company:lead?.companies||null,conversation:cr.data,message_history:mr.data||[],knowledge:kr.data||[]};let result;const started=Date.now();try{result=await providers.ai.generate(context);await logUsage(db,{provider:'openai',model:providers.ai.model,request_type:'draft',user_id:user.id,lead_id:lead?.id||null,conversation_id:body.conversationId,success:true,input_tokens:result.usage?.input_tokens||0,output_tokens:result.usage?.output_tokens||0,total_tokens:result.usage?.total_tokens||0,estimated_cost:estimatedCost(providers.ai.model,result.usage?.input_tokens||0,result.usage?.output_tokens||0),latency_ms:result.latency_ms||Date.now()-started,metadata:{}})}catch(e){await logUsage(db,{provider:'openai',model:providers.ai.model,request_type:'draft',user_id:user.id,lead_id:lead?.id||null,conversation_id:body.conversationId,success:false,error_code:e.code||'AI_ERROR',latency_ms:Date.now()-started,metadata:{}});return {status:e.code==='NOT_CONFIGURED'?503:502,body:{error:e.message,code:e.code,fallback:true}}}
  const draft=await db.from('ai_drafts').insert({conversation_id:body.conversationId,lead_id:lead?.id||null,draft_body:String(result.text||'').trim(),reasoning_summary:'Generated by configured server-side AI provider.',confidence:75,approval_status:'pending',mode:'ai_draft'}).select().single();if(draft.error)return {status:500,body:{error:'AI draft could not be stored'}};
  await db.from('notifications').insert({user_id:user.id,type:'ai_draft_ready',title:'AI draft ready',message:'A new AI response draft is waiting for approval.',lead_id:lead?.id||null,source_type:'ai_draft',source_id:draft.data.id});
  return {status:200,body:{draft:draft.data,fallback:false}};
}
async function emailSend({user,body}){
  requireRole(user,['admin','manager','sales']);if(!integrationLimiters.email.allow(user.id))return {status:429,body:{error:'Email rate limit exceeded'}};if(!body.outreachMessageId)return {status:400,body:{error:'outreachMessageId is required'}};const db=getAdminDb();
  const msg=await db.from('outreach_messages').select('id,campaign_id,lead_id,company_id,channel,message,subject,status,provider,provider_message_id,metadata,leads(name,companies(id,name,city,email,website)),companies(id,name,city,email,website)').eq('id',body.outreachMessageId).single();if(msg.error)return {status:404,body:{error:'Outreach message not found'}};
  if(msg.data.status==='sent'||msg.data.status==='delivered'||msg.data.status==='opened'||msg.data.status==='replied')return {status:200,body:{already_sent:true,message:msg.data}};
  if(msg.data.channel!=='email')return {status:400,body:{error:'Only email messages are executable in Phase 8.'}};
  const recipient=msg.data.leads?.companies?.email||msg.data.companies?.email;if(!recipient)return {status:422,body:{error:'No recipient email is available.'}};
  const key=msg.data.metadata?.idempotency_key||`outreach:${msg.data.id}`;const claim=await db.from('outreach_messages').update({status:'queued',queued_at:new Date().toISOString(),metadata:{...(msg.data.metadata||{}),idempotency_key:key}}).eq('id',msg.data.id).in('status',['pending','queued']).select().single();if(claim.error)return {status:409,body:{error:'Message could not be claimed safely.'}};
  const started=Date.now();try{const sent=await providers.email.send({to:recipient,subject:msg.data.subject||'Message from your team',text:msg.data.message,html:`<div>${String(msg.data.message).replace(/\n/g,'<br>')}</div>`,idempotencyKey:key});await db.from('outreach_messages').update({status:'sent',sent_at:new Date().toISOString(),provider:'resend',provider_message_id:sent.provider_message_id,error_message:null}).eq('id',msg.data.id);await db.from('integration_logs').insert({provider:'resend',operation:'send_email',status:'succeeded',related_lead_id:msg.data.lead_id,related_company_id:msg.data.company_id,metadata:{outreach_message_id:msg.data.id}});await db.from('notifications').insert({user_id:user.id,type:'email_sent',title:'Email sent',message:`Email sent to ${recipient}.`,lead_id:msg.data.lead_id,company_id:msg.data.company_id,source_type:'outreach_message',source_id:msg.data.id});return {status:200,body:{sent:true,provider_message_id:sent.provider_message_id}}}catch(e){await db.from('outreach_messages').update({status:'failed',failed_at:new Date().toISOString(),error_message:e.message}).eq('id',msg.data.id);await db.from('integration_logs').insert({provider:'resend',operation:'send_email',status:'failed',error_code:e.code||'EMAIL_ERROR',safe_error_message:e.message,retryable:Boolean(e.retryable),related_lead_id:msg.data.lead_id,related_company_id:msg.data.company_id,metadata:{outreach_message_id:msg.data.id,latency_ms:Date.now()-started}});await db.from('notifications').insert({user_id:user.id,type:'email_failed',title:'Email failed',message:e.message,lead_id:msg.data.lead_id,company_id:msg.data.company_id,source_type:'outreach_message',source_id:msg.data.id});return {status:e.code==='NOT_CONFIGURED'?503:e.code==='RATE_LIMIT'?429:502,body:{error:e.message,code:e.code,retryable:Boolean(e.retryable)}}}
}
export async function handleApi({path,req,body,user}){try{if(path==='/api/ai/analyze'&&req.method==='POST')return await aiAnalyze({user,body});if(path==='/api/ai/draft'&&req.method==='POST')return await aiDraft({user,body});if(path==='/api/email/send'&&req.method==='POST')return await emailSend({user,body});if(path==='/api/providers/health'&&req.method==='GET'){requireRole(user,['admin','manager']);return {status:200,body:{ai:await providers.ai.health({test:false}),email:await providers.email.health({test:false}),whatsapp:await providers.whatsapp.health(),sms:await providers.sms.health()}}}if(path==='/api/providers/test'&&req.method==='POST'){requireRole(user,['admin','manager']);const kind=body.provider;if(!['ai','email'].includes(kind))return {status:400,body:{error:'Only AI and email connection tests are implemented in Phase 8.'}};const result=kind==='ai'?await providers.ai.health({test:true}):await providers.email.health({test:true});const db=getAdminDb();await db.from('provider_connection_tests').insert({provider:result.provider,status:result.status==='connected'?'success':result.status==='not_configured'?'not_configured':'failed',error_code:result.error_code||null,safe_error_message:result.error_code||null,created_by:user.id});return {status:result.status==='error'?502:200,body:result}}return {status:404,body:{error:'Not found'}}}catch(e){return {status:e.status||500,body:{error:e.status===401?'Unauthorized':'Integration operation failed.'}}}}
