import crypto from 'node:crypto';
import {verifyHmacSignature,redactSecrets,safeError} from '../core/security.js';
import {getAdminDb} from '../core/db.js';

export async function handleWebhook({provider,eventType,rawBody,signature,secret,svixId,svixTimestamp,svixSignature}){
  const verified=provider==='resend'?verifyResendSignature(rawBody,svixId,svixTimestamp,svixSignature,secret):verifyHmacSignature(rawBody,signature,secret);
  if(!verified)return {status:401,body:{error:'Invalid webhook signature'}};
  let payload;try{payload=JSON.parse(rawBody)}catch{return {status:400,body:{error:'Invalid webhook payload'}}}
  eventType=payload.type||eventType;
  const db=getAdminDb();const externalEventId=String(payload.id||payload.event_id||payload.data?.id||'');const idempotencyKey=externalEventId||crypto.createHash('sha256').update(rawBody).digest('hex');
  const existing=await db.from('provider_events').select('id,status').eq('provider',provider).eq('idempotency_key',idempotencyKey).maybeSingle();if(existing.data)return {status:200,body:{validated:true,duplicate:true,event_id:existing.data.id}};
  const ins=await db.from('provider_events').insert({provider,event_type:eventType,external_event_id:externalEventId||null,status:'received',payload:redactSecrets(payload),normalized_event:{provider,event_type:eventType,external_event_id:externalEventId||null},signature_verified:true,idempotency_key:idempotencyKey}).select('id').single();if(ins.error)return {status:500,body:{error:'Provider event could not be persisted'}};
  if(provider==='resend') await processResendEvent(db,eventType,payload,ins.data.id);
  return {status:202,body:{provider,eventType,validated:true,event_id:ins.data.id}};
}
async function processResendEvent(db,eventType,payload,eventId){const data=payload.data||payload;const messageId=data.email_id||data.id||null;let status=null;if(/delivered/i.test(eventType))status='delivered';else if(/bounced/i.test(eventType))status='bounced';else if(/opened/i.test(eventType))status='opened';else if(/failed/i.test(eventType))status='failed';else if(/sent/i.test(eventType))status='sent';if(!messageId||!status){await db.from('provider_events').update({status:'ignored',processed_at:new Date().toISOString()}).eq('id',eventId);return}const msg=await db.from('outreach_messages').select('id,lead_id,company_id').eq('provider_message_id',messageId).maybeSingle();if(!msg.data){await db.from('provider_events').update({status:'processed',processed_at:new Date().toISOString(),normalized_event:{provider:'resend',event_type:eventType,message_id:messageId,unmatched:true}}).eq('id',eventId);return}const patch={status};if(status==='delivered')patch.delivered_at=new Date().toISOString();if(status==='opened')patch.opened_at=new Date().toISOString();if(status==='bounced')patch.bounced_at=new Date().toISOString();if(status==='failed')patch.failed_at=new Date().toISOString();await db.from('outreach_messages').update(patch).eq('id',msg.data.id);await db.from('provider_events').update({status:'processed',processed_at:new Date().toISOString(),normalized_event:{provider:'resend',event_type:eventType,message_id:messageId,outreach_message_id:msg.data.id}}).eq('id',eventId);}
export function verifyResendSignature(payload,id,timestamp,signature,secret){if(!id||!timestamp||!signature||!secret)return false;const ts=Number(timestamp);if(!Number.isFinite(ts)||Math.abs(Date.now()/1000-ts)>300)return false;const rawSecret=String(secret).replace(/^whsec_/,'');let key;try{key=Buffer.from(rawSecret,'base64')}catch{return false}const expected=crypto.createHmac('sha256',key).update(`${id}.${timestamp}.${payload}`).digest('base64');return String(signature).split(' ').some(part=>{const [version,value]=part.split(',');return version==='v1'&&value===expected})}
export function normalizeProviderEvent({provider,eventType,payload}){return {provider,event_type:eventType,payload:redactSecrets(payload),normalized_at:new Date().toISOString()}}
export function integrationFailure(error){return {status:500,body:safeError(error)}}
