import {AIProvider,ProviderError} from './provider.js';
import {serverConfig} from '../core/config.js';

const schema={type:'object',additionalProperties:false,properties:{intent:{type:'string'},confidence:{type:'number',minimum:0,maximum:1},recommended_action:{type:'string'},needs_human:{type:'boolean'},lead_score:{type:'number',minimum:0,maximum:100},suggested_service:{type:['string','null']},reason:{type:'string'}},required:['intent','confidence','recommended_action','needs_human','lead_score','suggested_service','reason']};

export class OpenAIProvider extends AIProvider{
  constructor(){super('openai');this.apiKey=serverConfig.openaiApiKey;this.model=serverConfig.openaiModel||'gpt-5.6-luna';this.timeoutMs=serverConfig.aiTimeoutMs||30000;}
  async health({test=false}={}){if(!this.apiKey)return {status:'not_configured',provider:this.name,model:this.model};if(!test)return {status:'configured',provider:this.name,model:this.model};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const r=await fetch('https://api.openai.com/v1/models',{headers:{authorization:`Bearer ${this.apiKey}`},signal:controller.signal});if(!r.ok)return {status:'error',provider:this.name,model:this.model,error_code:r.status===429?'RATE_LIMIT':'PROVIDER_ERROR'};return {status:'connected',provider:this.name,model:this.model}}catch(e){return {status:'error',provider:this.name,model:this.model,error_code:e.name==='AbortError'?'TIMEOUT':'NETWORK_ERROR'}}finally{clearTimeout(timer)}}
  async request(body){
    if(!this.apiKey) throw new ProviderError('AI provider is not configured.',{provider:this.name,operation:'request',code:'NOT_CONFIGURED'});
    const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);const started=Date.now();
    try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${this.apiKey}`},body:JSON.stringify(body),signal:controller.signal});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:{message:'Provider returned invalid JSON'}}}if(!r.ok){const code=r.status===429?'RATE_LIMIT':r.status>=500?'PROVIDER_UNAVAILABLE':'PROVIDER_ERROR';throw new ProviderError(data.error?.message||`OpenAI request failed (${r.status}).`,{provider:this.name,operation:'request',code,retryable:r.status===429||r.status>=500});}return {...data,latency_ms:Date.now()-started};}catch(e){if(e.name==='AbortError')throw new ProviderError('AI provider request timed out.',{provider:this.name,operation:'request',code:'TIMEOUT',retryable:true});if(e instanceof ProviderError)throw e;throw new ProviderError('AI provider network request failed.',{provider:this.name,operation:'request',code:'NETWORK_ERROR',retryable:true,cause:e});}finally{clearTimeout(timer)}
  }
  async analyze(context){const r=await this.request({model:this.model,input:[{role:'system',content:[{type:'input_text',text:'You are a CRM decision assistant. Return only the requested structured analysis. Never invent facts. If uncertain, set needs_human=true and lower confidence.'}]},{role:'user',content:[{type:'input_text',text:JSON.stringify(context)}]}],text:{format:{type:'json_schema',name:'crm_analysis',strict:true,schema}},max_output_tokens:600});const output=r.output_text||extractOutput(r);let parsed;try{parsed=JSON.parse(output)}catch(e){throw new ProviderError('AI returned invalid structured JSON.',{provider:this.name,operation:'analyze',code:'INVALID_STRUCTURED_OUTPUT'});}if(!schemaValidate(parsed))throw new ProviderError('AI structured output failed validation.',{provider:this.name,operation:'analyze',code:'INVALID_STRUCTURED_OUTPUT'});return {data:parsed,usage:r.usage||{},latency_ms:r.latency_ms};}
  async generate(context){const r=await this.request({model:this.model,input:[{role:'system',content:[{type:'input_text',text:'Write a concise, professional CRM reply in the requested language. Use only supplied context. Do not claim actions were taken. If the context is insufficient, say so briefly.'}]},{role:'user',content:[{type:'input_text',text:JSON.stringify(context)}]}],max_output_tokens:700});return {text:r.output_text||extractOutput(r),usage:r.usage||{},latency_ms:r.latency_ms};}
  async generateWebsite(context){const r=await this.request({model:this.model,input:[{role:'system',content:[{type:'input_text',text:'Generate a complete, production-quality single-page business website as one self-contained HTML document. Use only facts supplied in context. Do not invent testimonials, certifications, prices, addresses, phone numbers, emails, or claims. Use semantic HTML, accessible labels, responsive CSS, modern visual hierarchy, and vanilla JavaScript only. Do not include external build tooling, markdown fences, or explanatory text. The output must be only valid HTML beginning with <!doctype html>.'}]},{role:'user',content:[{type:'input_text',text:JSON.stringify(context)}]}],max_output_tokens:6000});const text=String(r.output_text||extractOutput(r)).trim().replace(/^```html\s*/i,'').replace(/```$/,'').trim();if(!/^<!doctype html>/i.test(text)&&!/^<html[\s>]/i.test(text))throw new ProviderError('Website generator returned invalid HTML.',{provider:this.name,operation:'generateWebsite',code:'INVALID_HTML'});return {text,usage:r.usage||{},latency_ms:r.latency_ms};}
}
function extractOutput(r){return (r.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||'').join('')}
function schemaValidate(x){return x&&typeof x.intent==='string'&&Number.isFinite(Number(x.confidence))&&Number(x.confidence)>=0&&Number(x.confidence)<=1&&typeof x.recommended_action==='string'&&typeof x.needs_human==='boolean'&&Number.isFinite(Number(x.lead_score))&&Number(x.lead_score)>=0&&Number(x.lead_score)<=100&&typeof x.reason==='string'&&(x.suggested_service===null||typeof x.suggested_service==='string')}
